ALTER TABLE PROCESSOCOTACAOFRETE ADD VALORPREVISTO NUMBER(13,2);

ALTER TABLE PROCESSOCOTACAOFRETE ADD VALORFECHADO NUMBER(13,2);

ALTER TABLE PROCESSOCOTACAOFRETE ADD TIPODEPRECO NUMBER(1,0) NULL;

ALTER TABLE PROCESSOCOTACAOFRETE ADD VALORMAXIMO NUMBER(13,2) NULL;

UPDATE PROCESSOCOTACAOFRETE SET TIPODEPRECO = CASE WHEN VALORFECHADO IS NULL THEN 0 ELSE 1 END;

COMMIT;

ALTER TABLE PROCESSOCOTACAOFRETE MODIFY TIPODEPRECO NUMBER(1,0) NOT NULL;

ALTER TABLE PROCESSOCOTACAOFRETE ADD "CADENCIA" NUMBER(13,3);

UPDATE PROCESSOCOTACAOFRETE SET 
CADENCIA = 0
WHERE CADENCIA IS NULL;	  
	  
ALTER TABLE COTACAOFRETE ADD "CADENCIA" NUMBER(13,3);

UPDATE COTACAOFRETE SET CADENCIA = 0
WHERE EXISTS(
	SELECT 1
	FROM COTACAO C INNER JOIN COTACAOITEM CI ON C.ID = CI.IDCOTACAO
	WHERE COTACAOFRETE.ID = C.ID
	AND SELECIONADA = 1
)
AND CADENCIA IS NULL;

Commit;	  
