ALTER TABLE REQUISICAOCOMPRA 
ADD (CODIGOGRUPODECOMPRA VARCHAR2(3 CHAR) );

ALTER TABLE REQUISICAOCOMPRA ADD MRP NUMBER(1,0);
ALTER TABLE REQUISICAOCOMPRA
ADD CONSTRAINT CHK_REQUISICAOCOMPRA_MRP CHECK 
(MRP BETWEEN 0 AND 1)
ENABLE;
UPDATE REQUISICAOCOMPRA SET MRP = 0;
ALTER TABLE REQUISICAOCOMPRA MODIFY MRP NUMBER(1,0) NOT NULL;

ALTER TABLE REQUISICAOCOMPRA 
ADD (GerouProcessoDeCotacao NUMBER(1,0));

UPDATE REQUISICAOCOMPRA SET GerouProcessoDeCotacao = 0
WHERE GerouProcessoDeCotacao IS NULL;
COMMIT;

--ALTERAÇÃO NA TABELA REQUISICAOCOMPRA (FIM)

--CRIAÇÃO DA TABELA PROCESSODECOTACAOITEM (INICIO)
CREATE TABLE PROCESSOCOTACAOITEM 
(
  ID NUMBER NOT NULL 
, IDPROCESSOCOTACAO NUMBER NOT NULL
, CODIGOPRODUTO VARCHAR2(18 BYTE) NOT NULL
, QUANTIDADE NUMBER(13, 3)  NOT NULL
, CODIGOUNIDADEMEDIDA VARCHAR2(3 CHAR) NOT NULL
, CONSTRAINT PK_PROCESSODECOTACAOITEM PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE PROCESSOCOTACAOITEM
ADD CONSTRAINT ITEM_PROCESSOCOTACAO FOREIGN KEY
(
  IDPROCESSOCOTACAO 
)
REFERENCES PROCESSOCOTACAO
(
  ID 
)
ENABLE;

ALTER TABLE PROCESSOCOTACAOITEM
ADD CONSTRAINT ITEM_PRODUTO FOREIGN KEY
(
  CODIGOPRODUTO 
)
REFERENCES PRODUTO
(
  CODIGO 
)
ENABLE;

ALTER TABLE PROCESSOCOTACAOITEM
ADD CONSTRAINT ITEM_UNIDADEMEDIDA FOREIGN KEY
(
  CODIGOUNIDADEMEDIDA 
)
REFERENCES UNIDADEMEDIDA
(
  CODIGOINTERNO 
)
ENABLE;

CREATE SEQUENCE PROCESSOCOTACAOITEM_ID_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1;

--CRIAÇÃO DA TABELA PROCESSODECOTACAOITEM (FIM)

--CRIAÇÃO DA TABELA PROCESSODECOTACAOITEMFRETE (INICIO)

CREATE TABLE PROCESSOCOTACAOITEMFRETE 
(
  ID NUMBER NOT NULL 
, CONSTRAINT PK_PROCESSOCOTACAOITEMFRETE PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE PROCESSOCOTACAOITEMFRETE
ADD CONSTRAINT PROCESSOITEMFRETE_ITEM FOREIGN KEY
(
  ID 
)
REFERENCES PROCESSOCOTACAOITEM
(
  ID 
)
ENABLE;
--CRIAÇÃO DA TABELA PROCESSOCOTACAOITEMFRETE (FIM)

--CRIAÇÃO DA TABELA PROCESSODOTACAOITEMMATERIAL (INICIO)
CREATE TABLE PROCESSOCOTACAOITEMMATERIAL 
(
  ID NUMBER NOT NULL 
, IDREQUISICAOCOMPRA NUMBER NOT NULL 
, CONSTRAINT PK_PROCESSOCOTACAOITEMMATERIAL PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE PROCESSOCOTACAOITEMMATERIAL
ADD CONSTRAINT FK_PROCESSOITEMMATERIAL_ITEM FOREIGN KEY
(
  ID 
)
REFERENCES PROCESSOCOTACAOITEM
(
  ID 
)
ENABLE;

ALTER TABLE PROCESSOCOTACAOITEMMATERIAL
ADD CONSTRAINT FK_PROCESSOITEMMAT_REQUISICAO FOREIGN KEY
(
  IDREQUISICAOCOMPRA 
)
REFERENCES REQUISICAOCOMPRA
(
  ID 
)
ENABLE;
--CRIAÇÃO DA TABELA PROCESSOCOTACAOITEMMATERIAL (FIM)


--IMPORTAÇÃO DOS DADOS DA TABELA DE PROCESSO DE COTAÇÃO PARA A TABELA DE ITENS (INICIO)
INSERT INTO PROCESSOCOTACAOITEM
(id,idprocessocotacao, codigoproduto, quantidade, codigounidademedida)
select processocotacaoitem_id_seq.nextval,pc.id, codigoproduto, quantidade, codigounidademedida
from processocotacao pc;

INSERT INTO PROCESSOCOTACAOITEMFRETE
(id)
select id
from processocotacaoitem
where idprocessocotacao in (select id from processocotacaofrete);


INSERT INTO PROCESSOCOTACAOITEMMATERIAL
(id, idrequisicaocompra)
select item.id, pcm.idrequisicaocompra
from processocotacaoitem item inner join processocotacaomaterial pcm
on item.idprocessocotacao = pcm.id;

--EXCLUSÃO DAS COLUNAS IMPORTADAS (INICIO)
ALTER TABLE PROCESSOCOTACAOMATERIAL DROP COLUMN IDREQUISICAOCOMPRA;
ALTER TABLE PROCESSOCOTACAO DROP COLUMN CODIGOPRODUTO;
ALTER TABLE PROCESSOCOTACAO DROP COLUMN CODIGOUNIDADEMEDIDA;
ALTER TABLE PROCESSOCOTACAO DROP COLUMN QUANTIDADE;
--EXCLUSÃO DAS COLUNAS IMPORTADAS (FIM)


--CRIAÇÃO DA TABELA COTACAOITEM (INICIO)
CREATE SEQUENCE COTACAOITEM_ID_SEQUENCE INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE TABLE COTACAOITEM 
(
  ID NUMBER NOT NULL 
, IDCOTACAO NUMBER NOT NULL 
, IDPROCESSOCOTACAOITEM NUMBER NOT NULL 
, QUANTIDADEDISPONIVEL NUMBER(13, 3) NOT NULL 
, VALORLIQUIDO NUMBER(13, 2) NOT NULL 
, VALORCOMIMPOSTOS NUMBER(13, 2) NOT NULL 
, OBSERVACOES CLOB 
, SELECIONADA NUMBER(1, 0) NOT NULL 
, QUANTIDADEADQUIRIDA NUMBER(13, 3) NULL 
, CONSTRAINT PK_COTACAOITEM PRIMARY KEY 
  (
    ID
  )
  ENABLE 
);

ALTER TABLE COTACAOITEM
ADD CONSTRAINT FK_COTACAOITEM_COTACAO FOREIGN KEY
(
  IDCOTACAO 
)
REFERENCES COTACAO
(
  ID 
)
ENABLE;

ALTER TABLE COTACAOITEM
ADD CONSTRAINT FK_COTACAOITEM_PROCESSOITEM FOREIGN KEY
(
  IDPROCESSOCOTACAOITEM 
)
REFERENCES PROCESSOCOTACAOITEM
(
  ID 
)
ENABLE;

ALTER TABLE COTACAOITEM
ADD CONSTRAINT CHK_COTACAOITEM_SELECIONADA CHECK 
(SELECIONADA BETWEEN 0 AND 1)
ENABLE;

--CRIAÇÃO DA TABELA COTACAOITEM (FIM)

--CRIAÇÃO DA TABELA COTACAOMATERIALITEM (INICIO)
CREATE TABLE COTACAOMATERIALITEM 
(
  ID NUMBER NOT NULL 
, CODIGOIVA VARCHAR2(2 BYTE) 
, MVA NUMBER(13, 2) 
, PRAZOENTREGA DATE NOT NULL 
, CONSTRAINT PK_COTACAOMATERIALITEM PRIMARY KEY 
  (
    ID
  )
  ENABLE 
);

ALTER TABLE COTACAOMATERIALITEM
ADD CONSTRAINT FK_COTACAOMATERIALITEM_COTACAO FOREIGN KEY
(
  ID
)
REFERENCES COTACAOITEM
(
  ID 
)
ENABLE;

ALTER TABLE COTACAOMATERIALITEM
ADD CONSTRAINT FK_COTACAOMATERIALITEM_IVA FOREIGN KEY
(
  CODIGOIVA 
)
REFERENCES IVA
(
  CODIGO 
)
ENABLE;

--CRIAÇÃO DA TABELA COTACAOMATERIALITEM (FIM)

--CRIAÇÃO DA TABELA COTACAOFRETEITEM (INICIO)
CREATE TABLE COTACAOFRETEITEM
(
  ID NUMBER NOT NULL 
, CONSTRAINT PK_COTACAOFRETEITEM PRIMARY KEY 
  (
    ID
  )
  ENABLE 
);

ALTER TABLE COTACAOFRETEITEM
ADD CONSTRAINT FK_COTACAOFRETEITEM_COTACAO FOREIGN KEY
(
  ID 
)
REFERENCES COTACAOITEM
(
  ID 
)
ENABLE;

--CRIAÇÃO DA TABELA COACAOFRETEITEM (FIM)

--CRIAÇÃO DA TABELA COTACAOITEMIMPOSTO (INICIO)
CREATE TABLE COTACAOITEMIMPOSTO 
(
  IDCOTACAOITEM NUMBER NOT NULL
, TIPOIMPOSTO NUMBER NOT NULL 
, ALIQUOTA NUMBER(4, 2) NOT NULL 
, VALOR NUMBER(13, 2) NOT NULL 
, CONSTRAINT PK_COTACAOITEMIMPOSTO PRIMARY KEY 
  (
    IDCOTACAOITEM    , 
    TIPOIMPOSTO 
  )
  ENABLE 
) ;

ALTER TABLE COTACAOITEMIMPOSTO
ADD CONSTRAINT FK_COTACAOITEMIMPOSTO_COTACAO FOREIGN KEY
(
  IDCOTACAOITEM
)
REFERENCES COTACAOITEM
(
  ID 
)
ENABLE;

--CRIAÇÃO DA TABELA COTACAOITEMIMPOSTO (FIM)

--CRIA REGISTROS NAS TABELAS DE ITEM DE COTAÇÃO DE FRETE
INSERT INTO COTACAOITEM
(id,idcotacao, idprocessocotacaoitem, quantidadedisponivel, valorliquido, valorcomimpostos, observacoes, selecionada, quantidadeadquirida)
select  cotacaoitem_id_sequence.nextval,cotacao.id, item.id, cotacao.quantidadedisponivel, cotacao.valorliquido, cotacao.valorcomimpostos, cotacao.observacoes,
cotacao.selecionada, cotacao.quantidadeadquirida
from fornecedorparticipante fp inner join processocotacaoitem item
on fp.idprocessocotacao = item.idprocessocotacao
inner join cotacao 
on fp.idcotacao = cotacao.id
inner join cotacaofrete
on cotacao.id = cotacaofrete.id;

INSERT INTO COTACAOFRETEITEM
(id)
select cotacaoitem.id
from fornecedorparticipante fp inner join processocotacaoitem item
on fp.idprocessocotacao = item.idprocessocotacao
inner join cotacao 
on fp.idcotacao = cotacao.id
inner join cotacaofrete 
on cotacao.id = cotacaofrete.id
inner join cotacaoitem on
cotacao.id = cotacaoitem.idcotacao
inner join cotacaofrete
on cotacao.id = cotacaofrete.id;


--CRIA REGISTROS NAS TABELAS DE ITEM DE COTAÇÃO DE MATERIAL
INSERT INTO COTACAOITEM
(id, idcotacao, idprocessocotacaoitem, quantidadedisponivel, valorliquido, valorcomimpostos, observacoes, selecionada, quantidadeadquirida)
select cotacaoitem_id_sequence.nextval, cotacao.id, item.id, cotacao.quantidadedisponivel, cotacao.valorliquido, cotacao.valorcomimpostos, cotacao.observacoes,
cotacao.selecionada, cotacao.quantidadeadquirida
from fornecedorparticipante fp inner join processocotacaoitem item
on fp.idprocessocotacao = item.idprocessocotacao
inner join cotacao 
on fp.idcotacao = cotacao.id
inner join cotacaomaterial
on cotacao.id = cotacaomaterial.id;

insert into cotacaomaterialitem
(id, codigoiva, mva, prazoentrega)
select cotacaoitem.id,cotacaomaterial.codigoiva, cotacaomaterial.mva, cotacaomaterial.prazoentrega
from fornecedorparticipante fp inner join processocotacaoitem item
on fp.idprocessocotacao = item.idprocessocotacao
inner join cotacao 
on fp.idcotacao = cotacao.id
inner join cotacaomaterial
on cotacao.id = cotacaomaterial.id
inner join cotacaoitem on
cotacao.id = cotacaoitem.idcotacao;

--CRIA REGISTROS NA TABELA DE IMPOSTOS
insert into cotacaoitemimposto
(idcotacaoitem, tipoimposto, aliquota, valor)
select cotacaoitem.id, tipoimposto, aliquota, valor
from cotacaoimposto inner join cotacaoitem
on cotacaoimposto.idcotacao = cotacaoitem.idcotacao;

COMMIT;

--EXCLUIR COLUNAS QUE FORAM MOVIDAS DA TABELA COTACAO
ALTER TABLE COTACAO DROP COLUMN SELECIONADA;
ALTER TABLE COTACAO DROP COLUMN VALORLIQUIDO;
ALTER TABLE COTACAO DROP COLUMN QUANTIDADEADQUIRIDA;
ALTER TABLE COTACAO DROP COLUMN QUANTIDADEDISPONIVEL;
ALTER TABLE COTACAO DROP COLUMN VALORCOMIMPOSTOS;
ALTER TABLE COTACAO DROP COLUMN OBSERVACOES;

--EXCLUIR COLUNAS QUE FORAM MOVIDAS DA TABELA COTACAOMATERIAL
ALTER TABLE COTACAOMATERIAL DROP COLUMN MVA;
ALTER TABLE COTACAOMATERIAL DROP COLUMN PRAZOENTREGA;
ALTER TABLE COTACAOMATERIAL DROP COLUMN CODIGOIVA;

--CRIAR COLUNA DE COMPRADOR NO PROCESSO DE COTACAO (INICIO)
ALTER TABLE PROCESSOCOTACAO 
ADD (LOGINCOMPRADOR VARCHAR2(12 BYTE) );

ALTER TABLE PROCESSOCOTACAO
ADD CONSTRAINT FK_PROCESSOCOTACAO_COMPRADOR FOREIGN KEY
(
  LOGINCOMPRADOR 
)
REFERENCES USUARIO
(
  LOGIN 
)
ENABLE;
--CRIAR COLUNA DE COMPRADOR NO PROCESSO DE COTACAO (FIM)

--RENOMEAÇÃO DA COLUNA VALORLIQUIDO PARA PRECO (INICIO)
ALTER TABLE COTACAOITEM RENAME COLUMN VALORLIQUIDO TO PRECO;
--RENOMEAÇÃO DA COLUNA VALORLIQUIDO PARA PRECO (FIM)

--CRIAÇÃO DA COLUNA VALOR LIQUIDO INICIAL NO ITEM DA COTAÇÃO (INICIO)
ALTER TABLE COTACAOITEM 
ADD (PRECOINICIAL NUMBER(13, 2) );

UPDATE COTACAOITEM SET PRECOINICIAL = PRECO
WHERE PRECOINICIAL IS NULL;
COMMIT;

ALTER TABLE COTACAOITEM  
MODIFY (PRECOINICIAL NOT NULL);
--CRIAÇÃO DA COLUNA VALOR LIQUIDO INICIAL NO ITEM DA COTAÇÃO (FIM)

--CRIAÇÃO DA COLUNA CUSTO NO ITEM DE COTAÇÃO (INICIO)
ALTER TABLE COTACAOITEM 
ADD (CUSTO NUMBER(13, 2) );
UPDATE COTACAOITEM SET CUSTO = VALORCOMIMPOSTOS WHERE CUSTO IS NULL;
COMMIT;
ALTER TABLE COTACAOITEM MODIFY CUSTO NUMBER(13,2) NOT NULL;
--CRIAÇÃO DA COLUNA CUSTO NO ITEM DE COTAÇÃO (FIM)

--CRIAÇÃO DA COLUNA Status na tabela RequisicaoCompra (INICIO)
ALTER TABLE REQUISICAOCOMPRA ADD Status NUMBER(1,0);
ALTER TABLE REQUISICAOCOMPRA ADD CONSTRAINT CHK_REQUISICAOCOMPRA_STATUS CHECK
(STATUS BETWEEN 1 AND 2);
UPDATE REQUISICAOCOMPRA SET STATUS = 1;
COMMIT;
ALTER TABLE REQUISICAOCOMPRA MODIFY Status NUMBER(1,0) NOT NULL;
--CRIAÇÃO DA COLUNA Status na tabela RequisicaoCompra (FIM)

--CRIAÇÃO DA COLUNA DataFechamento na tabela ProcessoCotacao (INICIO)
ALTER TABLE PROCESSOCOTACAO ADD DATAFECHAMENTO DATE;
UPDATE PROCESSOCOTACAO SET DATAFECHAMENTO = DATALIMITERETORNO
WHERE DATAFECHAMENTO IS NULL;
COMMIT;
--CRIAÇÃO DA COLUNA DataFechamento na tabela ProcessoCotacao (FIM)

--CRIAÇÃO DA TABELA HISTORICODEPRECO (INICIO)
CREATE TABLE HISTORICODEPRECO 
(
  ID NUMBER NOT NULL,
  IDCOTACAOITEM NUMBER(13, 2) NOT NULL 
, DATAHORA DATE NOT NULL 
, VALOR NUMBER(13, 2) NOT NULL,
CONSTRAINT PK_HISTORICODEPRECO PRIMARY KEY (ID) ENABLE,
CONSTRAINT FK_HISTORICOPRECO_COTACAOITEM FOREIGN KEY (IDCOTACAOITEM) REFERENCES COTACAOITEM (ID) ENABLE
);

CREATE SEQUENCE HISTORICODEPRECO_ID_SEQUENCE INCREMENT BY 1 START WITH 1;

--INSERE HISTÓRICO PARA O PREÇO INICIAL
INSERT INTO HISTORICODEPRECO
(ID, IDCOTACAOITEM, DATAHORA, VALOR)
SELECT HISTORICODEPRECO_ID_SEQUENCE.NEXTVAL, CI.ID,SYSDATE,PRECOINICIAL
FROM COTACAOITEM CI INNER JOIN COTACAOMATERIALITEM CIM
ON CI.ID = CIM.ID;

--INSERE HISTÓRICO PARA O PREÇO FINAL, CASO SEJA DIFERENTE DO PREÇO INICIAL
INSERT INTO HISTORICODEPRECO
(ID, IDCOTACAOITEM, DATAHORA, VALOR)
SELECT HISTORICODEPRECO_ID_SEQUENCE.NEXTVAL, CI.ID,SYSDATE,PRECO
FROM COTACAOITEM CI INNER JOIN COTACAOMATERIALITEM CIM
ON CI.ID = CIM.ID
WHERE PRECOINICIAL <> PRECO;

COMMIT;
--CRIAÇÃO DA TABELA HISTORICODEPRECO (FIM)

--ADICIONAR COLUNA NUMEROCOTACAO NA TABELA COTACAOMATERIAL (INICIO)
ALTER TABLE FORNECEDORPARTICIPANTE ADD NUMEROCOTACAO VARCHAR2(10 CHAR);
--ADICIONAR COLUNA NUMEROCOTACAO NA TABELA COTACAOMATERIAL (FIM)